name: test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RESOLUTION: '720p'
  FPS: 'native'


jobs:
  down:
    runs-on: ubuntu-latest
    name: "${{ matrix.name }}"
    defaults:
      run:
        shell: bash -l {0}
    
    strategy:
      fail-fast: false
      matrix:
#         fps: [10, 20, 'native']
        
        include:
          - name: Thor_Reaction
          
#           - name: Hocus_Pocus
#             url: 'https://www.youtube.com/watch?v=40SXyDeXV9Y'
# #             start: '0:05:20'
# #             end: '0:07:10'

#           - name: Peaky_Blinders
#             url: 'https://www.youtube.com/watch?v=LosFc1-eva4'
          
#           - name: Avengers_Endgame
#             url: 'https://www.youtube.com/watch?v=SdC-4x0-ESc'
          
#           - name: Hell_March_Indian_Army
#             url: 'https://www.youtube.com/watch?v=geKIYFkqkh0'

#           - name: V1
#           - name: V2
#           - name: V3
#           - name: V4
#           - name: V5
#           - name: V6
          - name: V7
#           - name: V8
#           - name: V9
#           - name: V10
#           - name: V11
          
    steps:

      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install aria2 ffmpeg python3-mutagen python3-pycryptodome p7zip-full
            pip3 install yt-dlp

      - name: Checkout Feelback
        uses: actions/checkout@v3
        with:
          repository: ahmedx3/Feelback
          token: ${{ secrets.TOKEN }}
      
      - name: Checkout This Repo
        uses: actions/checkout@v3
        with:
          path: download

      - name: Download Video
        working-directory: download
        if: matrix.url
        run: python3 download.py -f "$RESOLUTION" -o "${{ matrix.name }}" "${{ matrix.url }}"

      - name: Trim Video
        working-directory: download
        if: matrix.start && matrix.start
        run: |
          ffmpeg -i "${{ matrix.name }}.mp4" -ss "${{ matrix.start }}" -to "${{ matrix.end }}" -c copy "${{ matrix.name }}_out.mp4"
          mv "${{ matrix.name }}_out.mp4" "${{ matrix.name }}.mp4"

      - name: Copy Video File
        run: |
          cp "./download/videos/${{ matrix.name }}.mp4" . || echo ""
          cp "./download/${{ matrix.name }}.mp4" . || echo ""

      - name: create feelback conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,defaults
          auto-activate-base: false
          auto-update-conda: true
          activate-environment: feelback
          environment-file: requirements.yml

      - name: Export Env Variables
        run: |
          time=`date --utc '+%F:%Hh'`
          echo "TIME=${time}" >> $GITHUB_ENV
          
          DUMP_FORMAT="${{ matrix.name }}_${FPS}_fps_${RESOLUTION}_${time}"
          echo "DUMP_FORMAT=${DUMP_FORMAT}" >> $GITHUB_ENV
          
          tag=$(date --utc '+%Y%H%M%S')
          echo "TAG_NAME=${tag}" >> $GITHUB_ENV
          
          echo "FEELBACK_DUMP=feelback_${DUMP_FORMAT}.pickle" >> $GITHUB_ENV
          
          mkdir output
          
      - name: Process Video with Feelback
        if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
        run: python3 feelback_cli.py "${{ matrix.name }}.mp4" -f "$FPS" --dump "${FEELBACK_DUMP}" -vvv 
        
#       - name: Store Annotated Video [All]
#         if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
#         run: python3 feelback_cli.py "${{ matrix.name }}.mp4" --load "${FEELBACK_DUMP}" --output-annotations all  -o "./output/${DUMP_FORMAT}_all_annotations" -vvv  
        
#       - name: Store Annotated Video [IDs]
#         if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
#         run: python3 feelback_cli.py "${{ matrix.name }}.mp4" --load "${FEELBACK_DUMP}" --output-annotations ids  -o "./output/${DUMP_FORMAT}_ids_annotations" -vvv  
        
      - name: Store Annotated Video [Only Faces]
        if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
        run: python3 feelback_cli.py "${{ matrix.name }}.mp4" --load "${FEELBACK_DUMP}" --output-annotations none -o "./output/${DUMP_FORMAT}_position_annotations" -vvv  

      - name: Store Key Moments Plot
        if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
        run: python3 feelback_cli.py "${{ matrix.name }}.mp4" --load "${FEELBACK_DUMP}" --output-key-moments "./output/${DUMP_FORMAT}_key_moments.png" -vvv  

      - name: Prepare Backend Env
        run: |
          cat <<EOF >>.env
          FLASK_RUN_HOST="127.0.0.1"
          FLASK_RUN_PORT=5000
          FLASK_ENV=production
          UPLOAD_FOLDER=$PWD/uploads
          ANNOTATED_UPLOAD_FOLDER=$PWD/uploads_annotated
          THUMBNAILS_FOLDER=$PWD/thumbnails
          DATABASE_URL="sqlite:///$PWD/${DUMP_FORMAT}_database.db"
          EOF
          
          cat .env

      - name: Seed Backend Database
        if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
        run: python3 seed_backend.py "${{ matrix.name }}.mp4" --load-feelback "${FEELBACK_DUMP}"

      - name: Seed Backend Database [Thor_Reaction]
        if: matrix.name == 'Thor_Reaction'
        run: |
          cp ./download/videos/Thor_Trailer.mp4 .
          python3 seed_backend.py "${{ matrix.name }}.mp4" -t Thor_Trailer.mp4 --process
      
      - name: Seed Backend Database [V7]
        if: matrix.name == 'V7'
        run: |
          cp ./download/videos/V7_Slide_Trailer.mp4 .
          python3 seed_backend.py "${{ matrix.name }}.mp4" -t V7_Slide_Trailer.mp4 --process

      - name: Compress Backend Data
        run: |
          7z a "${DUMP_FORMAT}_thumbnails.zip" ./thumbnails
          7z a "${DUMP_FORMAT}_uploads_annotated.zip" ./uploads_annotated
          7z a "${DUMP_FORMAT}_uploads.zip" ./uploads
      
      - name: Encode Videos to reduce their size
        if: matrix.name != 'Thor_Reaction' && matrix.name != 'V7'
        run: |
          mkdir new
          cd output
          for video in *.mp4; do
            filename=`python -c "print('${video}'.rstrip('.mp4'))"`
            
            ffmpeg -i "${video}" -vcodec libx265 -crf 28 "../new/${filename}_x265.mp4"
            
            mv ../new/*.mp4 .
          done
      
      - run: ls -lRh
        continue-on-error: true
        if: always()
      
      - name: Release Files
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          tag_name: "${{ env.TAG_NAME }}_${{ matrix.name }}_${{ env.FPS }}"
          name: "${{ matrix.name }} Analysis - ${{ env.FPS }} fps"
          files: |
            ./output/*
            *.pickle
            *.db
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
